development:
  adapter: sqlite
  database: dev.db

test:
  adapter: sqlite
  database: test.db

development_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: management_development
  username: root
  password: root
  socket: /tmp/mysql.sock

development_mysql_jruby:
  adapter: jdbc
  url: "mysql://localhost/management_development?user=root&password=root"
  charset: utf8
  encoding: utf8

test_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: management_test
  username: root
  password: root
  socket: /tmp/mysql.sock
